### ISSUE TITLE
Epic : Plan and design both front end and backend features and timeline

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/dog-api#1]
As a **developer**, I can **see what needs to be done and when** so that I can **assign my time**.

Acceptance Criteria
- BackEnd ERD diagram must cover potential project outline
- FrontEnd wireframe diagrams for mobile and desktop should show most pages ideas
- Epics on project board with potential iterations fitting the time available

Tasks
- [ ] ERD diagram for back end
- [ ] Wireframes mobile and desktop for front end
- [ ] Project board set up to Epic level
