### ISSUE TITLE
Epic : API project set up and initial deploy - Backend

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/dog-api#10]
As a **developer**, I can **Get the project set up and deployed** so that I can **work on the project and check it still works in the deployed state**.

Acceptance Criteria
- All below tasks are complete and working
- Deployed version shows rocket image to show it is working

Tasks
- [ ] gitignore set up
- [ ] Procfile setup
- [ ] env.py set up
- [ ] install apps such as cloudinary/Pillow etc and add to settings
- [ ] secret key
- [ ] code media/image storage
- [ ] allowed hosts
- [ ] rest framework
- [ ] allauth
- [ ] CORS
- [ ] djdatabase url
- [ ] deployed to Heroku without any data
