### ISSUE TITLE
Epic : Set up front end repository and in the IDE

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/dog-api#25]
As a **developer**, I can **work on coding** so that I can **create the site**.

Acceptance Criteria
- working in gitpod
- empty shell deployed to Heroku
- basics of a frontend readme in place

Tasks
- [ ] Create github respository and set up in gitpod
- [ ] Set up Procfile
- [ ] deploy empty to heroku
- [ ] setup readme for the front end

**Comment by RachWalm** [comment]
Procfile not required for this project
