### ISSUE TITLE
Epic : Authentication - frontend

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/dog-api#27]
As a **, I can ** so that I can **.

Acceptance Criteria
- sign up/ sign in / sign out works
- Obvious if signed in or not
- access works and tokens refresh

Tasks
- [ ] Set up sign up/ sign in / sign out
- [ ] Show logged in status
- [ ] Code access tokens
