### ISSUE TITLE
Epic : README

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/dog-api#3]
As a **developer/future developer**, I can **have a document explaining the site** so that I can **understand the site and ensure others can understand it in future**.

Acceptance Criteria - to be written separately for front and back end
- Explains site design and intended use
- Covers all features and technologies used - accreditation of sources
- Gives information for future developers to add or make changes easily

Tasks
- [ ] Set up basic outline in backend repository
- [ ] Set up basic outline in frontend repository
- [ ] Have active tasks to complete as features / bugs occur
- [ ] Complete and review to make it a document rather than a load of entries strung together for backend
- [ ] Complete and review to make it a document rather than a load of entries strung together for backend
