### ISSUE TITLE
Epic : API sign in and out - Backend

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/dog-api#44]
As a **user**, I can **sign in and out** so that I can **have data that is protected from edit by everyone**.

Acceptance Criteria
- When logged out can get list of profiles, and view individual profiles
- when logged in can get list of profiles, and view individual profiles, can edit our own profiles
- Can't edit profiles of other users when logged in

Tasks
- [ ] add authentication urls to dog_api urls
- [ ] create and code permissions.py in dog_api
- [ ] test it works as anticipated
