### ISSUE TITLE
Epic : Submission

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/dog-api#8]
As a **developer**, I can **be happy to submit** so that I can **have the work accessed**.

Acceptance Criteria
- Debug is set to false
- Mentor is happy with submission

Tasks
- [ ] [#7](https://github.com/RachWalm/dog-api/issues/7)
- [ ] Check mentor happy with the submission
- [ ] Fill out submission form and submit
